version: "3"

services:
  vuefront:
    container_name: vue
    build: ./
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - backend

  admin:
    container_name: admin
    build: ./
    ports:
      - "8081:8081"
    network_mode: host
    depends_on:
      - backend

  backend:
    container_name: nodejs
    build: ./
    network_mode: host
    ports:
      - "5000:5000"
  #  depends_on:
  #     - db
  #
  # db:
  #   image: mysql:5
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: users
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: test123
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./docker/data/db:/var/lib/mysql
