version: "3"

services:
  vuefront:
    container_name: vue
    build: ./vuefront
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - backend

  admin:
    container_name: admin
    build: ./admin
    ports:
      - "8081:8081"
    network_mode: host
    depends_on:
      - backend

  backend:
    container_name: nodejs
    build: ./backend
    network_mode: host
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "6000:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080"
    depends_on: 
      - db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "7000:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "7070:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on: 
      - mongo

