apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
    labels:
        component: client
spec:
    replicas: 1
    selector:
        matchLabels:
            component: client
    template:
        metadata:
            labels:
                component: client
        spec:
            containers:
                -   name: client
                    image: 89253556478/web_app_demo:vuefront
                    ports:
                        - containerPort: 8080
                    env:
---
apiVersion: v1
kind: Service
metadata:
    name: client-cluster-ip-service
spec:
    type: LoadBalancer
    selector:
        component: client
    ports:
     -  port: 8080
        targetPort: 8080
        nodePort: 30002