apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
data:
  username: admin
  password: admin